site_name: Scanbot
repo_url: https://github.com/New-Horizons-SPM/scanbot
site_author: Julian Ceddia

nav:
    - Home: 'index.md'
    - Featured: 'featured.md'
    - Configuration: 'configuration.md'
    - Commands: 'commands.md'
    - Automation: 'automation.md'
    - Hooks: 'hooks.md'
    - About: 'about.md'
    - Contact: 'contact.md'
    
plugins:
    - mkdocs-video:
        is_video: True
        video_type: mp4
        video_loop: True
        