name: Windows Installation Test

on: [push, pull_request]

jobs:
  install:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
      name: Check out main repository code

    - name: Clone dependent repository
      run: git clone https://github.com/New-Horizons-SPM/nanonisTCP.git

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
          
    - name: Install dependent repository
      run: |
        cd nanonisTCP
        pip install .
        
    - name: Install node_modules and build the app
      env:
        CI: ""
      run: |
        cd scanbot/App
        npm install
        npm run build

    - name: Install the main application
      run: pip install .

    - name: Verify Installation of the main application
      run: scanbot --version
